### ISSUE TITLE
Repo does not build with OE 0.13

### ISSUE THREAD

**Issue by herveyw-msft** [openenclave/openenclave-curl#16]
Git clone, git submodule update --init

Then follow readme instructions; curl does not build as it cannot find the version of mbedtls that is part of OE.

**Comment by achamayou** [comment]
@herveyw-msft yes, #17 contains a minimal fix, which works with OE 0.15 on my machine. @letmaik will probably wince and suggest a proper cmake solution instead.

**Comment by herveyw-msft** [comment]
Thanks @achamayou, I will take a look at it. At this point, it seems a bit challenging to incorporate this project into our build system -- adding this project as an ExternalProject left me in a state where the nested curl submodule wasn't fetched. I am still investigating this, but temporarily took a different approach (but don't yet know if it worked).

**Comment by achamayou** [comment]
Fixed by #17
